export const COUNTRY_ZH_TO_EN = {
  '中国': 'China',
  '日本': 'Japan',
  '韩国': 'Korea',
  '朝鲜': 'Dem. Rep. Korea',
  '泰国': 'Thailand',
  '越南': 'Vietnam',
  '缅甸': 'Myanmar',
  '马来西亚': 'Malaysia',
  '新加坡': 'Singapore',
  '柬埔寨': 'Cambodia',
  '老挝': 'Lao PDR',
  '印度尼西亚': 'Indonesia',
  '菲律宾': 'Philippines',
  '文莱': 'Brunei',
  '印度': 'India',
  '尼泊尔': 'Nepal',
  '不丹': 'Bhutan',
  '巴基斯坦': 'Pakistan',
  '孟加拉国': 'Bangladesh',
  '斯里兰卡': 'Sri Lanka',
  '马尔代夫': 'Maldives',
  '蒙古': 'Mongolia',
  '哈萨克斯坦': 'Kazakhstan',
  '乌兹别克斯坦': 'Uzbekistan',
  '土耳其': 'Turkey',
  '以色列': 'Israel',
  '阿联酋': 'United Arab Emirates',
  '沙特阿拉伯': 'Saudi Arabia',
  '卡塔尔': 'Qatar',
  '伊朗': 'Iran',
  '约旦': 'Jordan',
  '黎巴嫩': 'Lebanon',
  '格鲁吉亚': 'Georgia',
  '亚美尼亚': 'Armenia',
  '阿塞拜疆': 'Azerbaijan',

  '英国': 'United Kingdom',
  '法国': 'France',
  '德国': 'Germany',
  '意大利': 'Italy',
  '西班牙': 'Spain',
  '葡萄牙': 'Portugal',
  '荷兰': 'Netherlands',
  '比利时': 'Belgium',
  '瑞士': 'Switzerland',
  '奥地利': 'Austria',
  '丹麦': 'Denmark',
  '瑞典': 'Sweden',
  '挪威': 'Norway',
  '芬兰': 'Finland',
  '冰岛': 'Iceland',
  '爱尔兰': 'Ireland',
  '希腊': 'Greece',
  '捷克': 'Czech Rep.',
  '波兰': 'Poland',
  '匈牙利': 'Hungary',
  '俄罗斯': 'Russia',
  '克罗地亚': 'Croatia',
  '塞尔维亚': 'Serbia',
  '斯洛文尼亚': 'Slovenia',
  '斯洛伐克': 'Slovakia',
  '保加利亚': 'Bulgaria',
  '罗马尼亚': 'Romania',
  '乌克兰': 'Ukraine',
  '立陶宛': 'Lithuania',
  '拉脱维亚': 'Latvia',
  '爱沙尼亚': 'Estonia',
  '卢森堡': 'Luxembourg',
  '马耳他': 'Malta',

  '美国': 'United States',
  '加拿大': 'Canada',
  '墨西哥': 'Mexico',
  '古巴': 'Cuba',
  '巴拿马': 'Panama',
  '哥斯达黎加': 'Costa Rica',

  '巴西': 'Brazil',
  '阿根廷': 'Argentina',
  '智利': 'Chile',
  '秘鲁': 'Peru',
  '哥伦比亚': 'Colombia',
  '乌拉圭': 'Uruguay',
  '玻利维亚': 'Bolivia',
  '厄瓜多尔': 'Ecuador',
  '委内瑞拉': 'Venezuela',

  '埃及': 'Egypt',
  '肯尼亚': 'Kenya',
  '南非': 'South Africa',
  '摩洛哥': 'Morocco',
  '坦桑尼亚': 'Tanzania',
  '突尼斯': 'Tunisia',
  '埃塞俄比亚': 'Ethiopia',
  '纳米比亚': 'Namibia',
  '博茨瓦纳': 'Botswana',
  '津巴布韦': 'Zimbabwe',
  '马达加斯加': 'Madagascar',

  '澳大利亚': 'Australia',
  '新西兰': 'New Zealand',
  '斐济': 'Fiji',
}

export function toEnglishCountry(zh) {
  return COUNTRY_ZH_TO_EN[zh] || zh
}
